accumulate_grad_batches: 1
activation: relu
arch: 2 7 4 3 5 6 3 4
attn_constraint: true
audio_num_mel_bins: 80
audio_sample_rate: 22050
base_config: configs/tts/transformer_tts.yaml
check_val_every_n_epoch: 10
clip_grad_norm: 1
data_dir: data/ljspeech
debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
dict_file: dict
dropout: 0.2
dur_predictor_kernel: 3
dur_predictor_layer: 2
enc_ffn_kernel_size: 9
enc_layers: 4
endless_ds: true
ffn_kernel_size: 9
ffn_padding: SAME
filter_size: 1024
fmax: 7600
fmin: 80
gen_dir_name: ''
gen_wav_denoise: false
griffin_lim_iters: 60
hidden_size: 256
hop_size: 256
indexed_ds: true
infer: false
lambda_dur: 1.0
lambda_energy: 1.0
lambda_pitch: 1.0
lambda_uv: 1.0
latent_size: 32
log_interval: 100
loud_norm: false
lr: 2.0
magnitude_power: 1
max_epochs: 1000
max_eval_sentences: 1
max_eval_tokens: 60000
max_frames: 1550
max_input_tokens: 200
max_sentences: -1
max_tokens: 28000
max_updates: 100000
mel_loss: l1
min_level_db: -100
n_fft: 1024
num_sanity_val_steps: 5
num_spk: 1
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pitch_loss: l1
pitch_predictor_layer: 5
power: 1
predictor_hidden: 256
predictor_layer_type: sepconv
predictor_sg: true
prenet_hidden_size: 32
pretrain_fs_ckpt: ''
profile_infer: false
raw_data_dir: data/raw/LJSpeech-1.1
ref_hidden_and_stride:
- 128,2
- 128,2
- 128,1
- 256,1
- 256,1
- 256,1
ref_level_db: 20
ref_norm_layer: bn_nonpad
resume_from_checkpoint: ''
save_ckpt: true
seed: 1234
sep_dur_loss: true
show_progress_bar: true
sort_by_len: true
stop_token_weight: 5.0
test_num: 100
test_set_name: test
train_set_name: train
use_amp: false
use_energy_embed: false
use_gt_dur: false
use_new_ffn: true
use_pitch_embed: true
use_ref_enc: false
use_ref_tfm: false
use_spk_embed: false
use_spk_id: false
use_training: false
use_uv: true
val_check_interval: 1000
valid_set_name: valid
vocoder: pwg
vocoder_ckpt: ''
warmup_updates: 2000
weight_decay: 0
win_size: 1024
work_dir: checkpoints/lightspeech
